### ISSUE TITLE
Firefox: Always opening new tab when logged in

### ISSUE THREAD

**Issue by swaglogger** [sixem/tiktok-download-buttons#1]
Seeing on firefox that when logged into an account clicking download button will always open a new tab. If i logout then downloads work properly. Seems to be working fine in chrome both logged in and out

**Comment by sixem** [comment]
This is actually a fallback that I had to add because TikTok appears to block some fetch requests, resulting in a 0 byte download if it were to be force-downloaded. I haven't been able to figure out exactly why this happens, but at least in my experience, it can happen when multiple requests are fired in a row (it never really happens on the first download, at least for me).

I'll continue to see if I can find a way to fix this, but as of right now, I haven't found a good solution.

**Comment by sixem** [comment]
The addon should use the API method [downloads.download](https://developer.chrome.com/docs/extensions/reference/downloads/#method-download) now, so downloading is a lot more stable now. Fallbacks are still present because Manifest V3 is a bit buggy, but the issue should be mostly gone.
