### ISSUE TITLE
[Bug] Naming setting not working for downloaded videos

### ISSUE THREAD

**Issue by grassfieldk** [sixem/tiktok-download-buttons#19]
The file name of the downloaded video remains the default even after entering "tt_{uploader}_{uploaded_s}" in the [Naming] section of the settings screen and clicking [Save].

**Comment by sixem** [comment]
Hi,

I tried it on both Chrome and Firefox and it seems to work for me, but there may be regional reasons for why this doesn't work for you... To troubleshoot, do you have access to the console output on TikTok, as in the console in the inspector for example?

If you do, if you could filter the output after `TTDB`, then attempt a download, it would let me know whether the web API failed or not. If the web API failed, then it should let you know. It should say something like `[TTDB] Got web API response {...}` if it's successful.

If the web API extraction fails, it'll attempt to download the raw video from the HTML. This doesn't have many placeholder associated with it compared to the API. I suspect this can be the reason why it isn't using the template, as it depends on getting the placeholder data from the API.

It would also be useful to know whether you have `rehydration` available (a set of script data that serves as the API data for the web version). There can be regional differences here, so I've only been able to test the web data extraction for myself, and this may be an issue. If you could execute:

```document.querySelector('script#__UNIVERSAL_DATA_FOR_REHYDRATION__');```

In the console when on TikTok, it should tell you whether you have the web API data available (if it returns an element instead of just `null` or whatever) or not.

In a future version, I should probably have some sort of warning when the API isn't working as expected, as that makes it hard to really utilize the templating, as we're lacking a lot of data, and that can lead to confusion as to why the template isn't working. I do think the issue is with the API extraction, and that for some regions, the data may be located elsewhere, and that may require additional checks for different regions.

**Comment by grassfieldk** [comment]
I was having trouble with Windows 11 and Chrome, including issues with incorrect filenames when downloading TikTok videos. I reinstalled Windows 10, and the problem seems to have been fixed. I think I can close this issue now.
