### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Rafael7bp** [sixem/tiktok-download-buttons#4]
I just want to say thankyou, your code is amazing.

**Comment by sixem** [comment]
Thank you :slightly_smiling_face:

Regarding the issue you made before editing: It should attempt to use the title as the filename (well, username and description/title/tags) as long as it's available (when using the API and so on). Due to the sanitizing of filenames, Cyrillic and Asian lettering are being filtered out, only allowing for Latin characters at the moment. I'll fix this in the next release, so other types of letters should be allowed then too.

I'm assuming you figured this out since you edited the issue, but if not, then that's the explanation :slightly_smiling_face:

If you have any other problems, feel free to create a new issue.
